### ISSUE TITLE
微信深度清理

### ISSUE THREAD

**Issue by coder-xiaomo** [coder-xiaomo/hexo-blog-comments#70]
https://fans.only4.work/post/news&information%2Fweixin-deep-clean 
 在座的各位应该都是被微信存储空间给折磨过的，动不动就几十个G的占比，非常的糟心，用着用着就存储空间不足了。 为什么微信这么占用空间，这是因为他最早的时候用的是点对点加密协议，简单来说就是你发送的消息直接传输给对方，中继服务器是不存的。所以之前微信的聊天记录也没法云同步，就需要本地...

**Comment by CuisineD0g** [comment]
你的链接失效了

**Comment by coder-xiaomo** [comment]
已修复
